CREATE TABLE config_table (
    config_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    config_key VARCHAR2(100) NOT NULL UNIQUE,
    config_value VARCHAR2(255) NOT NULL,
    description VARCHAR2(255),
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);