-- Create Users Table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    account_number VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Orders Table
CREATE TABLE payment_orders (
    order_id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    username VARCHAR2(50) NOT NULL, -- Linked to users.username
    recipient_bank_account VARCHAR2(20) NOT NULL,
    amount NUMBER(19,4) NOT NULL,
    currency VARCHAR2(3) DEFAULT 'INR' NOT NULL,
    description VARCHAR2(255),
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_order_user FOREIGN KEY (username) REFERENCES users(username),
    CONSTRAINT ck_order_amount CHECK (amount > 0),
    CONSTRAINT ck_order_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED'))
);

-- Create Indexes for Orders
CREATE INDEX idx_order_username ON payment_orders(username);
CREATE INDEX idx_order_status ON payment_orders(status);
CREATE INDEX idx_order_created_at ON payment_orders(created_at);

-- Create Idempotency Keys Table
CREATE TABLE idempotency_keys (
    idempotency_key VARCHAR2(100) PRIMARY KEY,
    order_id RAW(16) NOT NULL, -- Matches payment_orders.order_id
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT fk_idem_order FOREIGN KEY (order_id) REFERENCES payment_orders(order_id)
);

-- Create Index for Idempotency
CREATE INDEX idx_idem_created_at ON idempotency_keys(created_at);
