spring:
  application:
    name: order-service
  profiles:
    active: local

logging:
  file:
    name: logs/order-service.log
  logback:
    rollingpolicy:
      file-name-pattern: "logs/archived/order-service.%d{yyyy-MM-dd-HH}.log"
      max-history: 2
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"

  datasource:
    url: ${ORACLE_URL}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

  flyway:
    enabled: true
    baseline-on-migrate: true

rtps:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 1800000 # 30 minutes
  refreshExpirationMs: 604800000 # 7 days

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus
  endpoint:
    health:
      show-details: always

resilience4j:
  ratelimiter:
    instances:
      orderService:
        limitRefreshPeriod: 1m
        limitForPeriod: 100
        timeoutDuration: 5s
