spring:
  application:
    name: order-service
  profiles:
    active: local


  datasource:
    url: ${ORACLE_URL}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        hikari:
          minimumIdle: 5
          maximumPoolSize: 100

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      spring.json.trusted.packages: "*"
      spring.json.add.type.headers: true

  flyway:
    enabled: true
    baseline-on-migrate: true

rtps:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 1800000 # 30 minutes
  refreshExpirationMs: 604800000 # 7 days
  payment-gateway:
    url: ${PAYMENT_PROCESSOR_URL}
    path: ${PAYMENT_PROCESSOR_PATH}
    secret: ${ORDER_TO_PROCESSOR_SECRET}
  encryption:
    key: ${ENCRYPTION_KEY}

server:
  port: 8081
  tomcat:
    connection-timeout: 30000  # 30 seconds
    keep-alive-timeout: 60000  # 60 seconds

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus
  endpoint:
    health:
      show-details: always

resilience4j:
  ratelimiter:
    configs:
      default:
        limitRefreshPeriod: ${RATELIMITER_REFRESH_PERIOD}
        limitForPeriod: ${RATELIMITER_LIMIT_PERIOD}
        timeoutDuration: ${RATELIMITER_TIMEOUT}
    instances:
      orderService:
        baseConfig: default
